# This version of config.mk was generated by:
# ./configure
# Any changes made here will be lost if configure is re-run
SRCDIR = .
PREFIX = /usr/local
EXEC_PREFIX = $(PREFIX)
BINDIR = $(EXEC_PREFIX)/bin
DOCPREFIX = $(PREFIX)/share/doc
MANPREFIX = $(PREFIX)/share/man
SHAREPREFIX = $(PREFIX)/share
CC = cc
CFLAGS = -pipe -O2 -ffunction-sections -fdata-sections -fPIE
LDFLAGS = -Wl,-z,now -Wl,-z,relro
CFLAGS_STD = -std=c99 -D_POSIX_C_SOURCE=200809L -U_XOPEN_SOURCE -D_XOPEN_SOURCE=700 -DNDEBUG -D_FORTIFY_SOURCE=2
LDFLAGS_STD = -lc
CFLAGS_AUTO = -fstack-protector-all
LDFLAGS_AUTO = -Wl,--gc-sections -pie
CFLAGS_DEBUG = -U_FORTIFY_SOURCE -UNDEBUG -O0 -g3 -ggdb -Wall -Wextra -pedantic -Wno-missing-field-initializers -Wno-unused-parameter
CONFIG_HELP = 1
CFLAGS_TERMKEY = 
LDFLAGS_TERMKEY = -ltermkey 
CONFIG_CURSES = 1
CFLAGS_CURSES = -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 
LDFLAGS_CURSES = -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -lncursesw 
REGEX_SRC = text-regex-tre.c
CONFIG_TRE = 1
CFLAGS_TRE = -D_FORTIFY_SOURCE=2 
LDFLAGS_TRE = -ltre -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
CONFIG_LUA = 1
CFLAGS_LUA =  -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DLUA_COMPAT_5_3 -DLUA_COMPAT_ALL
LDFLAGS_LUA = -llua -lm 
CONFIG_LPEG = 0
CFLAGS_LPEG = 
LDFLAGS_LPEG = 
CONFIG_ACL = 1
CFLAGS_ACL = 
LDFLAGS_ACL = -lacl
CONFIG_SELINUX = 0
CFLAGS_SELINUX = 
LDFLAGS_SELINUX = 
CFLAGS_LIBC = -DHAVE_MEMRCHR=1
